server:
  port: 9000

logging:
  level:
    root: info
    org:
      springframework:
        web: trace
        security: info
        oauth2: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth-demo?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: Xy&278721524
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 123
            client-secret: 123
